# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Code"
  url = "#code"
  weight = 30

[[main]]
  name = "Promote"
  url = "#promote"
  weight = 40

[[main]]
  name = "Live"
  url = "#live"
  weight = 50

[[main]]
  name = "Dwnld"
  url = "#dwnld"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 80

[[main_right]]
  name = "<i class=\"fab fa-youtube\" style=\"color: #FF0000; font-size: 1.5rem; line-height: 2\"></i>"
  url = "https://www.youtube.com/channel/UCJz0UPnJlNgT-KNLnPbcUrQ?sub_confirmation=1"
  weight = 10

[[main_right]]
  name = "<i class=\"fab fa-github\" style=\"color: #333; font-size: 1.5rem; line-height: 2\"></i>"
  url = "https://github.com/scaleya"
  weight = 20

[[main_right]]
  name = "<i class=\"fab fa-telegram\" style=\"color:	#0088CC; font-size: 1.5rem; line-height: 2\"></i>"
  url = "https://t.me/Scaleya_Public_Group"
  weight = 30